const images = [
    {
      src: "1.PNG",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum ex quis rhoncus lacinia. Nam porttitor tempus elit, quis tristique arcu vestibulum vel. Nulla sollicitudin fermentum nisl, sed pellentesque elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse fringilla vel dolor in gravida. Sed suscipit suscipit urna sit amet volutpat. Pellentesque ut euismod lectus. Maecenas a massa quis ex fringilla pretium. Phasellus eget lorem sem. Suspendisse potenti. ",
    },
    { src: "2.PNG", description: "Sample 2" },
    { src: "3.PNG", description: "Sample 1" },
    { src: "4.PNG", description: "Sample 2" },
    { src: "5.PNG", description: "Sample 1" },
    { src: "6.PNG", description: "Sample 2" },
    { src: "7.PNG", description: "Sample 1" },
    { src: "8.PNG", description: "Sample 2" },
    { src: "9.PNG", description: "Sample 1" },
    {
      src: "1.PNG",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum ex quis rhoncus lacinia. Nam porttitor tempus elit, quis tristique arcu vestibulum vel. Nulla sollicitudin fermentum nisl, sed pellentesque elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse fringilla vel dolor in gravida. Sed suscipit suscipit urna sit amet volutpat. Pellentesque ut euismod lectus. Maecenas a massa quis ex fringilla pretium. Phasellus eget lorem sem. Suspendisse potenti. ",
    },
    { src: "2.PNG", description: "Sample 2" },
    { src: "3.PNG", description: "Sample 1" },
    { src: "4.PNG", description: "Sample 2" },
    { src: "5.PNG", description: "Sample 1" },
    { src: "6.PNG", description: "Sample 2" },
    { src: "7.PNG", description: "Sample 1" },
    { src: "8.PNG", description: "Sample 2" },
    { src: "9.PNG", description: "Sample 1" },
    {
      src: "1.PNG",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum ex quis rhoncus lacinia. Nam porttitor tempus elit, quis tristique arcu vestibulum vel. Nulla sollicitudin fermentum nisl, sed pellentesque elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse fringilla vel dolor in gravida. Sed suscipit suscipit urna sit amet volutpat. Pellentesque ut euismod lectus. Maecenas a massa quis ex fringilla pretium. Phasellus eget lorem sem. Suspendisse potenti. ",
    },
    { src: "2.PNG", description: "Sample 2" },
    { src: "3.PNG", description: "Sample 1" },
    { src: "4.PNG", description: "Sample 2" },
    { src: "5.PNG", description: "Sample 1" },
    { src: "6.PNG", description: "Sample 2" },
    { src: "7.PNG", description: "Sample 1" },
    { src: "8.PNG", description: "Sample 2" },
    { src: "9.PNG", description: "Sample 1" },
    {
      src: "1.PNG",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum ex quis rhoncus lacinia. Nam porttitor tempus elit, quis tristique arcu vestibulum vel. Nulla sollicitudin fermentum nisl, sed pellentesque elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse fringilla vel dolor in gravida. Sed suscipit suscipit urna sit amet volutpat. Pellentesque ut euismod lectus. Maecenas a massa quis ex fringilla pretium. Phasellus eget lorem sem. Suspendisse potenti. ",
    },
    { src: "2.PNG", description: "Sample 2" },
    { src: "3.PNG", description: "Sample 1" },
    { src: "4.PNG", description: "Sample 2" },
    { src: "5.PNG", description: "Sample 1" },
    { src: "6.PNG", description: "Sample 2" },
    { src: "7.PNG", description: "Sample 1" },
    { src: "8.PNG", description: "Sample 2" },
    { src: "9.PNG", description: "Sample 1" },
    {
      src: "1.PNG",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum ex quis rhoncus lacinia. Nam porttitor tempus elit, quis tristique arcu vestibulum vel. Nulla sollicitudin fermentum nisl, sed pellentesque elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse fringilla vel dolor in gravida. Sed suscipit suscipit urna sit amet volutpat. Pellentesque ut euismod lectus. Maecenas a massa quis ex fringilla pretium. Phasellus eget lorem sem. Suspendisse potenti. ",
    },
    { src: "2.PNG", description: "Sample 2" },
    { src: "3.PNG", description: "Sample 1" },
    { src: "4.PNG", description: "Sample 2" },
    { src: "5.PNG", description: "Sample 1" },
    { src: "6.PNG", description: "Sample 2" },
    { src: "7.PNG", description: "Sample 1" },
    { src: "8.PNG", description: "Sample 2" },
    { src: "9.PNG", description: "Sample 1" },
    {
      src: "1.PNG",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum ex quis rhoncus lacinia. Nam porttitor tempus elit, quis tristique arcu vestibulum vel. Nulla sollicitudin fermentum nisl, sed pellentesque elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse fringilla vel dolor in gravida. Sed suscipit suscipit urna sit amet volutpat. Pellentesque ut euismod lectus. Maecenas a massa quis ex fringilla pretium. Phasellus eget lorem sem. Suspendisse potenti. ",
    },
    { src: "2.PNG", description: "Sample 2" },
    { src: "3.PNG", description: "Sample 1" },
    { src: "4.PNG", description: "Sample 2" },
    { src: "5.PNG", description: "Sample 1" },
    { src: "6.PNG", description: "Sample 2" },
    { src: "7.PNG", description: "Sample 1" },
    { src: "8.PNG", description: "Sample 2" },
    { src: "9.PNG", description: "Sample 1" },
    {
      src: "1.PNG",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum ex quis rhoncus lacinia. Nam porttitor tempus elit, quis tristique arcu vestibulum vel. Nulla sollicitudin fermentum nisl, sed pellentesque elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse fringilla vel dolor in gravida. Sed suscipit suscipit urna sit amet volutpat. Pellentesque ut euismod lectus. Maecenas a massa quis ex fringilla pretium. Phasellus eget lorem sem. Suspendisse potenti. ",
    },
    { src: "2.PNG", description: "Sample 2" },
    { src: "3.PNG", description: "Sample 1" },
    { src: "4.PNG", description: "Sample 2" },
    { src: "5.PNG", description: "Sample 1" },
    { src: "6.PNG", description: "Sample 2" },
    { src: "7.PNG", description: "Sample 1" },
    { src: "8.PNG", description: "Sample 2" },
    { src: "9.PNG", description: "Sample 1" },
    {
      src: "1.PNG",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum ex quis rhoncus lacinia. Nam porttitor tempus elit, quis tristique arcu vestibulum vel. Nulla sollicitudin fermentum nisl, sed pellentesque elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse fringilla vel dolor in gravida. Sed suscipit suscipit urna sit amet volutpat. Pellentesque ut euismod lectus. Maecenas a massa quis ex fringilla pretium. Phasellus eget lorem sem. Suspendisse potenti. ",
    },
    { src: "2.PNG", description: "Sample 2" },
    { src: "3.PNG", description: "Sample 1" },
    { src: "4.PNG", description: "Sample 2" },
    { src: "5.PNG", description: "Sample 1" },
    { src: "6.PNG", description: "Sample 2" },
    { src: "7.PNG", description: "Sample 1" },
    { src: "8.PNG", description: "Sample 2" },
    { src: "9.PNG", description: "Sample 1" },
    {
      src: "1.PNG",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum ex quis rhoncus lacinia. Nam porttitor tempus elit, quis tristique arcu vestibulum vel. Nulla sollicitudin fermentum nisl, sed pellentesque elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse fringilla vel dolor in gravida. Sed suscipit suscipit urna sit amet volutpat. Pellentesque ut euismod lectus. Maecenas a massa quis ex fringilla pretium. Phasellus eget lorem sem. Suspendisse potenti. ",
    },
    { src: "2.PNG", description: "Sample 2" },
    { src: "3.PNG", description: "Sample 1" },
    { src: "4.PNG", description: "Sample 2" },
    { src: "5.PNG", description: "Sample 1" },
    { src: "6.PNG", description: "Sample 2" },
    { src: "7.PNG", description: "Sample 1" },
    { src: "8.PNG", description: "Sample 2" },
    { src: "9.PNG", description: "Sample 1" },
    {
      src: "1.PNG",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum ex quis rhoncus lacinia. Nam porttitor tempus elit, quis tristique arcu vestibulum vel. Nulla sollicitudin fermentum nisl, sed pellentesque elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse fringilla vel dolor in gravida. Sed suscipit suscipit urna sit amet volutpat. Pellentesque ut euismod lectus. Maecenas a massa quis ex fringilla pretium. Phasellus eget lorem sem. Suspendisse potenti. ",
    },
    { src: "2.PNG", description: "Sample 2" },
    { src: "3.PNG", description: "Sample 1" },
    { src: "4.PNG", description: "Sample 2" },
    { src: "5.PNG", description: "Sample 1" },
    { src: "6.PNG", description: "Sample 2" },
    { src: "7.PNG", description: "Sample 1" },
    { src: "8.PNG", description: "Sample 2" },
    { src: "9.PNG", description: "Sample 1" },
    {
      src: "1.PNG",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum ex quis rhoncus lacinia. Nam porttitor tempus elit, quis tristique arcu vestibulum vel. Nulla sollicitudin fermentum nisl, sed pellentesque elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse fringilla vel dolor in gravida. Sed suscipit suscipit urna sit amet volutpat. Pellentesque ut euismod lectus. Maecenas a massa quis ex fringilla pretium. Phasellus eget lorem sem. Suspendisse potenti. ",
    },
    { src: "2.PNG", description: "Sample 2" },
    { src: "3.PNG", description: "Sample 1" },
    { src: "4.PNG", description: "Sample 2" },
    { src: "5.PNG", description: "Sample 1" },
    { src: "6.PNG", description: "Sample 2" },
    { src: "7.PNG", description: "Sample 1" },
    { src: "8.PNG", description: "Sample 2" },
    { src: "9.PNG", description: "Sample 1" },
    {
      src: "1.PNG",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum ex quis rhoncus lacinia. Nam porttitor tempus elit, quis tristique arcu vestibulum vel. Nulla sollicitudin fermentum nisl, sed pellentesque elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse fringilla vel dolor in gravida. Sed suscipit suscipit urna sit amet volutpat. Pellentesque ut euismod lectus. Maecenas a massa quis ex fringilla pretium. Phasellus eget lorem sem. Suspendisse potenti. ",
    },
    { src: "2.PNG", description: "Sample 2" },
    { src: "3.PNG", description: "Sample 1" },
    { src: "4.PNG", description: "Sample 2" },
    { src: "5.PNG", description: "Sample 1" },
    { src: "6.PNG", description: "Sample 2" },
    { src: "7.PNG", description: "Sample 1" },
    { src: "8.PNG", description: "Sample 2" },
    { src: "9.PNG", description: "Sample 1" },
    {
      src: "1.PNG",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum ex quis rhoncus lacinia. Nam porttitor tempus elit, quis tristique arcu vestibulum vel. Nulla sollicitudin fermentum nisl, sed pellentesque elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse fringilla vel dolor in gravida. Sed suscipit suscipit urna sit amet volutpat. Pellentesque ut euismod lectus. Maecenas a massa quis ex fringilla pretium. Phasellus eget lorem sem. Suspendisse potenti. ",
    },
    { src: "2.PNG", description: "Sample 2" },
    { src: "3.PNG", description: "Sample 1" },
    { src: "4.PNG", description: "Sample 2" },
    { src: "5.PNG", description: "Sample 1" },
    { src: "6.PNG", description: "Sample 2" },
    { src: "7.PNG", description: "Sample 1" },
    { src: "8.PNG", description: "Sample 2" },
    { src: "9.PNG", description: "Sample 1" },
    {
      src: "1.PNG",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum ex quis rhoncus lacinia. Nam porttitor tempus elit, quis tristique arcu vestibulum vel. Nulla sollicitudin fermentum nisl, sed pellentesque elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse fringilla vel dolor in gravida. Sed suscipit suscipit urna sit amet volutpat. Pellentesque ut euismod lectus. Maecenas a massa quis ex fringilla pretium. Phasellus eget lorem sem. Suspendisse potenti. ",
    },
    { src: "2.PNG", description: "Sample 2" },
    { src: "3.PNG", description: "Sample 1" },
    { src: "4.PNG", description: "Sample 2" },
    { src: "5.PNG", description: "Sample 1" },
    { src: "6.PNG", description: "Sample 2" },
    { src: "7.PNG", description: "Sample 1" },
    { src: "8.PNG", description: "Sample 2" },
    { src: "9.PNG", description: "Sample 1" },
    {
      src: "1.PNG",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum ex quis rhoncus lacinia. Nam porttitor tempus elit, quis tristique arcu vestibulum vel. Nulla sollicitudin fermentum nisl, sed pellentesque elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse fringilla vel dolor in gravida. Sed suscipit suscipit urna sit amet volutpat. Pellentesque ut euismod lectus. Maecenas a massa quis ex fringilla pretium. Phasellus eget lorem sem. Suspendisse potenti. ",
    },
    { src: "2.PNG", description: "Sample 2" },
    { src: "3.PNG", description: "Sample 1" },
    { src: "4.PNG", description: "Sample 2" },
    { src: "5.PNG", description: "Sample 1" },
    { src: "6.PNG", description: "Sample 2" },
    { src: "7.PNG", description: "Sample 1" },
    { src: "8.PNG", description: "Sample 2" },
    { src: "9.PNG", description: "Sample 1" },
    {
      src: "1.PNG",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum ex quis rhoncus lacinia. Nam porttitor tempus elit, quis tristique arcu vestibulum vel. Nulla sollicitudin fermentum nisl, sed pellentesque elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse fringilla vel dolor in gravida. Sed suscipit suscipit urna sit amet volutpat. Pellentesque ut euismod lectus. Maecenas a massa quis ex fringilla pretium. Phasellus eget lorem sem. Suspendisse potenti. ",
    },
    { src: "2.PNG", description: "Sample 2" },
    { src: "3.PNG", description: "Sample 1" },
    { src: "4.PNG", description: "Sample 2" },
    { src: "5.PNG", description: "Sample 1" },
    { src: "6.PNG", description: "Sample 2" },
    { src: "7.PNG", description: "Sample 1" },
    { src: "8.PNG", description: "Sample 2" },
    { src: "9.PNG", description: "Sample 1" },
  ].map((image) => ({ ...image, clicked: false }));

  export default images;